### ISSUE TITLE
Project Health Report loops

### ISSUE THREAD

**Issue by Gwindalmir** [malware-dev/MDK-SE#205] opened 2020-08-18 01:36 UTC
In relation to the previous issue I reported, #204, I went ahead and moved the entire project directory to a different location.
When I opened the .sln in VS, it gave me a notification that the whitelist cache needed to be updated.
When I click "repair", it does whatever it does and pops up _again_ asking to be updated.

I have to click Cancel to break out of the infinite loop of prompting.

![image](https://user-images.githubusercontent.com/1127170/90460416-8cdb2d80-e0b8-11ea-9c29-71bbcddfd63e.png)

**Comment by malware-dev** [comment] 2020-08-18 06:18
Can you upload - or otherwise provide me, if you don't want to make your project public - the project so I have a reproduction?

**Comment by malware-dev** [comment] 2020-08-18 06:19
I'm kinda guessing that it's the whitelist updater that fails.

**Comment by Gwindalmir** [comment] 2020-08-18 07:31
All I did was create a new project, and paste the example code from: https://github.com/malware-dev/MDK-SE/wiki/Text-Panels-and-Drawing-Sprites#final-code-listing
There's nothing else.

I just created a new solution, with these settings:
![image](https://user-images.githubusercontent.com/1127170/90483267-54077c80-e0e9-11ea-84f0-118c553157ff.png)
![image](https://user-images.githubusercontent.com/1127170/90483419-8a44fc00-e0e9-11ea-9e5c-e5dd7da5c7ae.png)

Then right clicked and selected "MDK Deploy Script."

**Comment by exo-pla-net** [comment] 2022-10-07 17:33
Same issue for me, when also attempting to save and load the project on Google Drive.

"The whitelist cache must be updated", always pops up, and no error is displayed.

**Comment by malware-dev** [comment] 2024-07-12 17:02
Closing because this site is being archived due to complete replacement at https://github.com/malforge/mdk2. If issue persist, please create new issue there.

**Closed by malware-dev** 2024-07-12 17:02 UTC
