### ISSUE TITLE
Minifyer skips some variables when written below Main()

### ISSUE THREAD

**Issue by Skimt** [malware-dev/MDK-SE#32] opened 2017-08-17 01:26 UTC
I suppose this behavior is expected if it minifies from top-to-bottom, going through A to Z. I tried to see if I could balance _characters written_ and _instruction count_ by writing a sort of library of strings that has to be repeated throughout the script. Since I found it messy to keep the library above Program(), I moved it below Main(). As a result, not all of the variables got abbreviated upon deploy.

```
string
            _TARGET = "Target",
            _RANGE = "Range",
            _METEORS = "Meteors",
            _MISSILES = "Missiles",
            _SMALLSHIPS = "SmallShips",
            _LARGESHIPS = "LargeShips",
            _CHARACTERS = "Characters",
            _STATIONS = "Stations",
            _NEUTRALS = "Neutrals",
            _ON = "_On",
            _OFF = "_Off",
            _ONOFF = "OnOff",
            _ATMOSPHERIC = "atmospheric",
            _HYDROGEN = "hydrogen",
            _ION = "ion";
```

string y="Target",_RANGE="Range",_METEORS="Meteors",_MISSILES="Missiles",C="SmallShips",D="LargeShips",E="Characters",F="Stations",G="Neutrals",H="_On",_OFF="_Off",J="OnOff",K="atmospheric",L="hydrogen",M="ion";

When I moved the collection of strings back up to the top, above Program(), it was no longer an issue. 

**Easiest solution:** User writes variables at the top where they are expected to be found procedurally.

**Comment by malware-dev** [comment] 2017-08-17 04:53
Ok, that's strange. The positioning of those shouldn't matter. That's most certainly a bug, thank you. Would you mind enclosing a script project where the problem is happening? Thank you in advance.

I cannot promise this bug will be fixed for v1.0 though.

**Comment by Skimt** [comment] 2017-08-17 05:56
I shoved this into a script of its own and deployed. It should yield the same result. I apologize if by "enclosing a script project" I misunderstood you and shouldn't have copy-pasted a part of the script here. 

Ps. If this is a very inefficient way of writing this, I wouldn't know. I haven't tested it yet so as to compare it to the old version in which I didn't use strings like this. For all I know it could very well end up in an unnecessary amount of instruction counts just to save 100 characters worth :D 

```
using Sandbox.Game.EntityComponents;
using Sandbox.ModAPI.Ingame;
using Sandbox.ModAPI.Interfaces;
using SpaceEngineers.Game.ModAPI.Ingame;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System;
using VRage.Collections;
using VRage.Game.Components;
using VRage.Game.ModAPI.Ingame;
using VRage.Game.ObjectBuilders.Definitions;
using VRage.Game;
using VRageMath;

namespace IngameScript {
    partial class Program : MyGridProgram {

        /* ################################
        # GOBALS
        ################################ */

        int intervals, interval, turretCount;

        /* ################################
        # PROGRAM
        ################################ */

        public Program() {
        }

        /* ################################
        # MAIN
        ################################ */

        void Main(string argument) {

            Intervals();
            TurretProcedure();

        }

        /* ################################
        # PROCEDURES
        ################################ */

        // Turret blocks  
        void TurretProcedure() {
            var blocks = new List<IMyLargeTurretBase>();
            GridTerminalSystem.GetBlocksOfType(blocks, Filter);
            var count = blocks.Count;
            if (CanRun(count, interval) && turretCount != count) {
                // only update when there's a change in number of turrets from last run
                turretCount = count;
                string[] settings = { };
                int range = 0;
                string[] interior = {
                    _TARGET+_METEORS+_ON,
                    _TARGET+_MISSILES+_ON,
                    _TARGET+_SMALLSHIPS+_ON,
                    _TARGET+_LARGESHIPS+_OFF,
                    _TARGET+_CHARACTERS+_ON,
                    _TARGET+_STATIONS+_OFF,
                    _TARGET+_NEUTRALS+_OFF
                };
                string[] gatling = {
                    _TARGET+_METEORS+_OFF,
                    _TARGET+_MISSILES+_ON,
                    _TARGET+_SMALLSHIPS+_ON,
                    _TARGET+_LARGESHIPS+_ON,
                    _TARGET+_CHARACTERS+_ON,
                    _TARGET+_STATIONS+_ON,
                    _TARGET+_NEUTRALS+_OFF
                };
                string[] missile = {
                    _TARGET+_METEORS+_OFF,
                    _TARGET+_MISSILES+_OFF,
                    _TARGET+_SMALLSHIPS+_ON,
                    _TARGET+_LARGESHIPS+_ON,
                    _TARGET+_CHARACTERS+_OFF,
                    _TARGET+_STATIONS+_ON,
                    _TARGET+_NEUTRALS+_OFF
                };
                foreach (var block in blocks) {
                    if (block is IMyLargeInteriorTurret) {
                        settings = interior;
                        range = 150;
                    } else if (block is IMyLargeGatlingTurret) {
                        settings = gatling;
                        range = 1000;
                    } else {
                        settings = missile;
                        range = 1000;
                    }
                    block.SetValueFloat(_RANGE, range);
                    block.EnableIdleRotation = false;
                    foreach (var setting in settings) {
                        block.ApplyAction(setting);
                    }
                }
            }
        }

        /* ################################
        # TOOLS
        ################################ */

        // Intervals
        void Intervals() {
            intervals++;
            interval = 2;
        }

        // Common filter used when retrieving terminals
        bool Filter(IMyTerminalBlock block) {
            return block.CubeGrid == Me.CubeGrid;
        }

        // Checks if there's more than zero items and if the item set should run at the given interval
        bool CanRun(int count, int interval) {
            bool run = false;
            if (count > 0) {
                interval = interval + 1;
                if (intervals % interval == 0) {
                    run = true;
                }
            }
            return run;
        }

        /* ################################
        # STRING LIBRARY
        ################################ */

        string
            _TARGET = "Target",
            _RANGE = "Range",
            _METEORS = "Meteors",
            _MISSILES = "Missiles",
            _SMALLSHIPS = "SmallShips",
            _LARGESHIPS = "LargeShips",
            _CHARACTERS = "Characters",
            _STATIONS = "Stations",
            _NEUTRALS = "Neutrals",
            _ON = "_On",
            _OFF = "_Off",
            _ONOFF = "OnOff",
            _ATMOSPHERIC = "atmospheric",
            _HYDROGEN = "hydrogen",
            _ION = "ion";

    }
}
```

**Comment by malware-dev** [comment] 2017-08-17 06:50
Well I would have preferred if you'd actually zipped your solution, but I can probably make this work ;)

PS: You should probably make those strings `const string`, I assume they'll never actually change during runtime.

**Comment by Wicorel** [comment] 2017-08-21 02:22
I am having a similar issue.

**Comment by malware-dev** [comment] 2017-10-25 13:30
I'm so sorry these things take so long, it will happen, I promise...

**Comment by malware-dev** [comment] 2017-12-07 06:40
Since the minifier is being completely rewritten from scratch, this issue is no longer relevant.

**Closed by malware-dev** 2017-12-07 06:40 UTC
Labels: bug
