### ISSUE TITLE
Suggestion: Remove comments as an alternative to minify

### ISSUE THREAD

**Issue by Gwindalmir** [malware-dev/MDK-SE#100] opened 2018-12-23 09:24 UTC
As an alternative to full minifying, it would be nice to just remove comments from a script.
This would be handy for scripts that are near the size limit, so that the author can of course keep their own comments locally, but still want to keep the script editable for others, but below the script size limit.

This feature should not affect the readme.cs file, so the contents of that would always be injected.
Perhaps also keep special comments, like XML style (ie. ///)

**Comment by Georgiks** [comment] 2019-04-19 16:10
Would love it!

**Comment by the-vindicar** [comment] 2020-01-29 18:53
Any progress on this issue? It'd be an incentive to actually comment your scripts, since those wouldn't eat up precious character limit.

**Comment by malware-dev** [comment] 2020-01-29 19:25
The problem is this:


_I_ have no use for it. Thus I have no incentive to _make_ it.


I'm not saying no (if so I'd be straight forward with it and simply close this issue), but I'm not saying yes either. Very likely not any time soon, especially since I'm not really scripting much myself these days.

**Comment by Wicorel** [comment] 2020-01-29 21:13
This is what I used to make my code smaller pre-MDK days:

https://codebeautify.org/csharpviewer

**Comment by the-vindicar** [comment] 2020-01-29 22:53
Ah, so it's not like there is some arcane reason preventing it entirely?
That's alright, then. Maybe, if I have time...

**Comment by malware-dev** [comment] 2020-01-30 09:22
Any contribution would be very welcome. If you do this though; make sure it's an _option_. The default composer should not change the code more than necessary.

**Closed** 2020-02-05 16:39 UTC
Labels: Pull Request in review, Request, enhancement
