### ISSUE TITLE
[Pre] Warning 'Analyzer assembly '...\MDKAnalyzer.dll' depends on 'netstandard, Version=...'

### ISSUE THREAD

**Issue by ntnn** [malware-dev/MDK-SE#63] opened 2018-04-05 15:33 UTC
The error list lists the following warning:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	IDE1003	Analyzer assembly 'C:\Users\ntnn\AppData\Local\Microsoft\VisualStudio\15.0_6cada3d9\Extensions\nd4vzr3b.vl4\Analyzers\MDKAnalyzer.dll' depends on 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.	3D Printer		1	Active
```

Visual Studio version: 15.6.5
MDK version: 1.1.3

Intellisense, code analysis and deployment works without issues - it's just the warning taking up space in the error list.

**Comment by malware-dev** [comment] 2018-04-07 11:38
I'm sorry, I can't seem to reproduce this issue.

**Comment by ntnn** [comment] 2018-04-08 19:15
I was able to fix the warning by installing `NETStandard.Library` in version 2.0.0 through VS' builtin NuGet - this however has to be repeated for every project in the solutions.

A clean install of VS did not fix the issue.

Installing `NETStandard.Library` through system nuget/choco did not resolve the issue globally either.

Most likely its an issue with my specific system, I'll see if I can reproduce it on another system.

**Comment by malware-dev** [comment] 2018-04-14 11:10
Any update to this? If not I'm gonna close it for lack of reproduction - especially due to @baratgabor's allusion to the problem being related to issue #62, that MDK wasn't loading properly at all.

**Comment by ntnn** [comment] 2018-04-14 17:25
I was able to reproduce the problem on a different system.

Both systems are virtually the same, one is a laptop with 8GiB RAM, an i7 and a mobile Nvidia Graphics Card, the station has 16GiB RAM, AMD FX8320 and a 1070.

OS: Windows 10 (latest updates released to my systems)
VS: Visual Studio Community Edition 2017 v15.6.6
MDK: Latest version (0.1.6)

Steps to reproduce:
- Install Visual Studio Community Edition with the .NET desktop development workload (nothing added or removed)
- Install MDK SE plugin
- Create new project through `File -> New -> New Project`
- Select `Ingame Script`
- Enable showing error list through `View -> Error List`
- One warning will be visible noting the message noted in the opening post

**Comment by Skimt** [comment] 2018-04-28 22:14
I loaded an old SE solution where I had 3 projects. Was asked to update MDK, and did. Opened the solution again, and noticed the IDE1003 warning on all 3 projects. 

- Tried to install NuGet package netstandard library 2.0.2. Didn't work.
- Tried to install NuGet package netstandard library 2.0.0. Didn't work. 
- Tried to update Visual Studio Community 2017. Didn't work. 
- Tried to install Visual Studio SDK. Didn't work. 

Perhaps unrelated. When I opened up Bootstrapper.cs I got the following "Warning CS0618 'MDK' is obsolete: 'Use MDKFactory directly.' MainShipScript \MDK\Bootstrapper.cs 19 & 20". I tried to changed the MDK class to MDKFactory in ONE of the three projects, but it seems to only have suppressed the CS0618 warning that appeared in that particular project. 

I tried to add SE as analyzers and restart the project but now I've got 30 or so similar warnings, so I'm just dropping this experiment of mine before my computer begins to grow legs and kick me in the ass.

**Comment by malware-dev** [comment] 2018-04-29 09:33
@Skimt The CS0618 warning is deliberate and unrelated. You will probably have noticed by now that new projects uses the new class. Obviously I cannot go back and change _old_ projects. It is a harmless warning and as you figured out is easily fixed manually by changing that single line.

As for the dll warning it doesn't matter _what_ you do to your projects, as it is not related to the projects but the MDK analyzer itself. Somehow. But since I'm unable to reproduce the issue myself I'm equally unable to fix it.

**Comment by Skimt** [comment] 2018-07-05 23:08
The issue was not resolved with the methods above, but got resolved by physically editing the project file by adding `<Reference Include="netstandard" />` in `ItemGroup`. The problem persist in newly created projects as well as old projects.

**Comment by malware-dev** [comment] 2018-07-06 18:15
It doesn't make any sense to me. The analyzer should not be affected by the actual project it's analyzing. I don't get this. I'm also still not getting the issue itself. ☹️

**Comment by malware-dev** [comment] 2018-07-06 19:05
_I finally managed to reproduce_. Had to go on another computer to do so. However That - at least - is something.

**Comment by Skimt** [comment] 2018-07-06 19:06
Scratch what I said last time, the warning is back for me again. I feel like nothing makes sense anymore.

**Comment by malware-dev** [comment] 2018-07-06 19:08
It has something to do with the references for the analyzer itself.

**Comment by ntnn** [comment] 2018-07-21 11:10
That update resolved the issue for me. Not closing in case @Skimt has a different experience.

@malware-dev Thanks!

**Comment by Skimt** [comment] 2018-07-21 13:57
Seems like the update resolved the issue for me as well. I think you can go ahead and close it.

**Comment by malware-dev** [comment] 2018-07-21 14:14
Awesome guys, thank you. That was one half of the issues solved, at least.

**Closed by malware-dev** 2018-07-21 14:14 UTC
Labels: bug
