### ISSUE TITLE
Missing picture for Steam Workshop.

### ISSUE THREAD

**Issue by Elfiwolfe** [malware-dev/MDK-SE#15] opened 2017-08-02 06:40 UTC
Deploying from MDK to SE.
Then uploading the project will not have 
![thumb](https://user-images.githubusercontent.com/22664974/28860783-c5d4f6ec-7712-11e7-9b41-b7c8f83199af.png)
the c# pictures of scripts on the workshop.

**Comment by malware-dev** [comment] 2017-08-03 08:46
Fixed for the next release

**Comment by Elfiwolfe** [comment] 2017-08-07 14:18
It puts thumbwithpromotion into the folder.  I had to rename to thumb to get it to upload to workshop.

**Comment by malware-dev** [comment] 2017-08-07 16:14
I can't reproduce. How'd you manage that?

**Comment by Elfiwolfe** [comment] 2017-08-07 23:53
Um.. I think this is a close.. this was a projected created before the fix.

**Comment by malware-dev** [comment] 2017-08-08 06:24
Ok, I see. Closing again then.

**Closed by malware-dev** 2017-08-08 06:24 UTC
Labels: bug
